name: Generate Configs
on:
  workflow_dispatch:
jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd ./scripts
      - name: Create config
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: 'config.json'
          json: ${{ vars.CONFIG }}
      - name: Create AdGuard Config
        shell: bash
        run: |
          ./create-adguardhome.sh
          cat ./output/adguardhome/lancache.conf
